apiVersion: v1
data:
  agent.yaml: |
    server:
      http_listen_port: 8080
      log_level: debug
    metrics:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 15s
        external_labels:
          cluster: default
      configs:
        - name: spanmetrics
          remote_write:
            - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
              basic_auth:
                username: $M_USERNAME
                password: $M_PASSWORD
          scrape_configs:
            - job_name: local_scrape
              static_configs:
                - targets: ['127.0.0.1:8080']
                  labels:
                    cluster: 'default'
                    container: 'minikube-g-agent'
                    pod: 'grafana-agent-traces'
    traces:
      configs:
        - batch:
            send_batch_size: 1000
            timeout: 5s
          name: default
          receivers:
            jaeger:
              protocols:
                grpc: null
                thrift_binary: null
                thrift_compact: null
                thrift_http: null
              remote_sampling:
                strategy_file: /etc/agent/strategies.json
                tls:
                  insecure: true
            opencensus: null
            otlp:
              protocols:
                grpc:
                http:
            zipkin: null
          attributes:
            actions:
              - action: upsert
                key: env
                value: minikube
          remote_write:
            - basic_auth:
                password: $T_PASSWORD
                username: $T_USERNAME
              endpoint: tempo-eu-west-0.grafana.net:443
              retry_on_failure:
                enabled: false
          spanmetrics:
            handler_endpoint: 0.0.0.0:8889
          service_graphs:
            enabled: true
          scrape_configs:
            - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: false
  strategies.json: '{"default_strategy": {"param": 0.001, "type": "probabilistic"}}'
kind: ConfigMap
metadata:
  name: grafana-agent-traces
  namespace: default